baseurl = "https://jmfavaro2.netlify.com/"
title = "Jean-Marc's Blog"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Jean-Marc Favaro"
disqusShortname = "XXX"
googleAnalytics = "XXX"

[Author]
    name = "Jean-Marc Favaro"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Le blog de JM"
    description = "Ghostwriter example description"
    github = "https://github.com/XXX"
    gitlab = "https://gitlab.com/XXX"
    linkedin = "https://fr.linkedin.com/in/favaro-jean-marc-0748149"
    gplus = "https://google.com/+XXX"
    twitter = "https://twitter.com/jm_favaro"
    stackoverflow = "https://stackoverflow.com/users/XXX/YYY"
    email = "jmfavaro@yahoo.fr"
    opengraph = true
    shareTwitter = true
    shareFacebook = false
    shareGooglePlus = false
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3
